
-- Update incident_suspects table with new fields
ALTER TABLE public.incident_suspects 
ADD COLUMN IF NOT EXISTS mugshot TEXT,
ADD COLUMN IF NOT EXISTS cid TEXT,
ADD COLUMN IF NOT EXISTS confiscated_items TEXT,
ADD COLUMN IF NOT EXISTS evidences TEXT,
ADD COLUMN IF NOT EXISTS plead TEXT DEFAULT 'Not Guilty',
ADD COLUMN IF NOT EXISTS fine INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS jail INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS tag TEXT,
ADD COLUMN IF NOT EXISTS is_hut BOOLEAN DEFAULT false;
